### ISSUE TITLE
Use of Bazel build system forces dependency on dated release

### ISSUE THREAD

**Issue by sanmai-NL** [vaticle/typedb-driver-rust#35]
## Problem to Solve

Rust programmers may have problems with the currently released version, of November last year. They cannot depend on the current mainline revision, since Rust Cargo cannot add this repository as dependency. That is because it misses a `Cargo.toml`. You might have thought it to be superfluous given your use of Bazel. Bazel is not a conventional build system for Rust programmers, though.

## Proposed Solution

Supply a `Cargo.toml`, perhaps alongside Bazel artifacts, if Bazel is to stay.

**Comment by flyingsilverfin** [comment]
Hi @sanmai-NL you're right that we haven't made a new release in a while. In the future you can expect there to be more regular releases to Cargo so that you don't have to use Bazel yourself and we also don't have to include a separate cargo build in the project. 

@dmitrii-ubskii let's schedule a release next week when I'm back in the office?

**Comment by sanmai-NL** [comment]
@flyingsilverfin A separate Cargo build of the product, seems like you think it'd be costly to maintain. Is there evidence for that? And for practical solutions, can't Bazel output a `Cargo.toml`?

**Comment by clembu** [comment]
> To depend on the latest stable version, depend on the latest release which is published to crates.io.

Here is my output from `cargo add typedb-client`:
```
    Updating crates.io index
      Adding typedb-client v0.1.2 to dependencies.
error: failed to select a version for `uuid`.
    ... required by package `typedb-client v0.1.2`
    ... which satisfies dependency `typedb-client = "^0.1.2"` of package `mediabay v0.0.0 (H:\dev\apps\mediabay\src-tauri)`
versions that meet the requirements `^1.1.2` are: 1.4.0, 1.3.4, 1.3.3, 1.3.2, 1.3.1, 1.3.0, 1.2.2, 1.2.1, 1.1.2

the package `typedb-client` depends on `uuid`, with features: `private_getrandom` but `uuid` does not have these features.


all possible versions conflict with previously selected packages.

  previously selected package `uuid v1.2.1`
    ... which satisfies dependency `uuid = "^1.2"` of package `tao v0.16.0`
    ... which satisfies dependency `tao = "^0.16.0"` of package `wry v0.24.1`
    ... which satisfies dependency `wry = "^0.24.1"` of package `tauri-runtime-wry v0.14.0`
    ... which satisfies dependency `tauri-runtime-wry = "^0.14.0"` of package `tauri v1.4.1`
    ... which satisfies dependency `tauri = "^1.4.1"` of package `mediabay v0.0.0 (H:\dev\apps\mediabay\src-tauri)`

failed to select a version for `uuid` which could resolve this conflict
```

It seems `private_getrandom` was removed as an available feature from `1.2.0`, and was discouraged as a direct dependency from the start (recommending to depend on `rng` instead). I understand the version on crates.io is more than 9 months old now, and reading the code at https://github.com/vaticle/dependencies/blob/master/library/crates/Cargo.toml#L64C61-L64C61 I can assume this is no longer an issue today (and hasn't been since January since you switched to a Cargo-first dependency description for rust).

I'd rather not lock my whole project to old versions of everything just for typedb to be able to access the `private_getrandom` feature of `uuid`, so I'm wondering what my options are here if I want to start using typedb in my tauri app. If I were to build a crate from source, is master a good place to checkout, is there a particular commit/tag that would work as a 'latest stable-enough' for simple plaintext connections and read/write data and schema queries?

**Comment by dmitrii-ubskii** [comment]
> reading the code at https://github.com/vaticle/dependencies/blob/master/library/crates/Cargo.toml#L64C61-L64C61 I can assume this is no longer an issue today (and hasn't been since January since you switched to a Cargo-first dependency description for rust).

Unfortunately, this is still an issue. `rules_rust` resolves all features that we use up front, and since `rng` implies `private_getrandom`, the latter still ends up in the generated cargo manifest. This is something we should be able to handle when assembling the crate for deployment though.

**Comment by flyingsilverfin** [comment]
We believe we have resolved all of our cargo toml conversion issues, and are publishing to `crates.io` every release. Our release cadence should now be more active and hopefully this resolves the issue of wanting to depend on  a 'more recent' driver version. Please let us know if you need an unreleased feature immediately and we can try to orchestrate a release for you then.
